### ISSUE TITLE
Setup.py also installs pytest

### ISSUE THREAD

**Issue by sevdog** [fireeye/stringsifter#5]
`setup.py` by using every requirements aslo installs `pytest` which should be a development requirement and should not be propagated also in production build.

**Comment by phtully** [comment]
Thanks for the good suggestion - I agree and also think that the dev/prod differentiation will be more important in future releases if and when we release code for users to train their own models in DIY fashion.

**Comment by ewalshfeye** [comment]
Fixed in version 1.20201201
